platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet
    tag: '2-sdk'

inputs:
  - name: pal-tracker
  - name: version

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |

    function stop_mysql {
      service mysql stop
    }

    trap stop_mysql EXIT

    export DEBIAN_FRONTEND="noninteractive"
    apt-get update
    apt-get -y install mysql-server
    service mysql start

    mysql -uroot < pal-tracker/databases/tracker/create_databases.sql

    curl https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/4.2.0/flyway-commandline-4.2.0-linux-x64.tar.gz | tar xvz
    flyway-*/flyway -url="jdbc:mysql://localhost:3306/tracker_dotnet_test" -locations=filesystem:pal-tracker/databases/tracker -user=tracker_dotnet -password=password clean migrate

    home_path=$(pwd)
    tmp_path=/tmp/pal-tracker
    
    mkdir -p $tmp_path
    cp pal-tracker/manifest-*.yml $tmp_path

    dotnet test ./pal-tracker/test/PalTrackerTests

    dotnet publish ./pal-tracker/src/PalTracker --configuration Release \
      --output $tmp_path/src/PalTracker/bin/Release/netcoreapp2.0/publish
    
    tar -C $tmp_path/ -cvzf ./build-output/pal-tracker-$(cat ./version/number).tgz .
    